### ISSUE TITLE
Creating a Logo

### ISSUE THREAD

**Issue by tjulises** [giovaniv/bar-chart-lib#1]
Hello @giovaniv ,

I've noticed this project doesn't have a logo yet!!!
I can help up with that, I'd like to contribute with this 
awesome project by delivering a simple and clean logo
that adjusts to the project idea!!!
What do you think? let me know!

thanks!!!

**Comment by giovaniv** [comment]
Hello, how are you? Hope that you're well.

I really liked your interested in this project but I can't accept because
is for study purpose and a challenge that one of the majority rules is do
everything alone and without any help. I will start another project and in
this, I will be able to receive a contribution from you if you want it but
this, unfortunately, I can't accept.

Thanks!

*Giovani Raymundo de Vasconcelos*
E-Mail: giovaniv@gmail.com
Mobile: 1-778-580-9024

**Comment by tjulises** [comment]
It's ok I understand, if you have project and need a logo, I could help up with that! let me know! thanks!!! 
@giovaniv
